// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.36.0
// source: proto/plugin.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetMetaRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMetaRequest) Reset() {
	*x = GetMetaRequest{}
	mi := &file_proto_plugin_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMetaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMetaRequest) ProtoMessage() {}

func (x *GetMetaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_plugin_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMetaRequest.ProtoReflect.Descriptor instead.
func (*GetMetaRequest) Descriptor() ([]byte, []int) {
	return file_proto_plugin_proto_rawDescGZIP(), []int{0}
}

type GetMetaResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// JSON-encoded pluginsdk.Meta
	MetaJson      []byte `protobuf:"bytes,1,opt,name=meta_json,json=metaJson,proto3" json:"meta_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMetaResponse) Reset() {
	*x = GetMetaResponse{}
	mi := &file_proto_plugin_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMetaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMetaResponse) ProtoMessage() {}

func (x *GetMetaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_plugin_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMetaResponse.ProtoReflect.Descriptor instead.
func (*GetMetaResponse) Descriptor() ([]byte, []int) {
	return file_proto_plugin_proto_rawDescGZIP(), []int{1}
}

func (x *GetMetaResponse) GetMetaJson() []byte {
	if x != nil {
		return x.MetaJson
	}
	return nil
}

type ValidateRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// JSON-encoded raw plugin config
	ConfigJson    []byte `protobuf:"bytes,1,opt,name=config_json,json=configJson,proto3" json:"config_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateRequest) Reset() {
	*x = ValidateRequest{}
	mi := &file_proto_plugin_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateRequest) ProtoMessage() {}

func (x *ValidateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_plugin_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateRequest.ProtoReflect.Descriptor instead.
func (*ValidateRequest) Descriptor() ([]byte, []int) {
	return file_proto_plugin_proto_rawDescGZIP(), []int{2}
}

func (x *ValidateRequest) GetConfigJson() []byte {
	if x != nil {
		return x.ConfigJson
	}
	return nil
}

type ValidateResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// JSON-encoded validated config
	ConfigJson    []byte `protobuf:"bytes,1,opt,name=config_json,json=configJson,proto3" json:"config_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateResponse) Reset() {
	*x = ValidateResponse{}
	mi := &file_proto_plugin_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateResponse) ProtoMessage() {}

func (x *ValidateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_plugin_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateResponse.ProtoReflect.Descriptor instead.
func (*ValidateResponse) Descriptor() ([]byte, []int) {
	return file_proto_plugin_proto_rawDescGZIP(), []int{3}
}

func (x *ValidateResponse) GetConfigJson() []byte {
	if x != nil {
		return x.ConfigJson
	}
	return nil
}

type DiscoverRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// JSON-encoded raw plugin config
	ConfigJson    []byte `protobuf:"bytes,1,opt,name=config_json,json=configJson,proto3" json:"config_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DiscoverRequest) Reset() {
	*x = DiscoverRequest{}
	mi := &file_proto_plugin_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiscoverRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiscoverRequest) ProtoMessage() {}

func (x *DiscoverRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_plugin_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiscoverRequest.ProtoReflect.Descriptor instead.
func (*DiscoverRequest) Descriptor() ([]byte, []int) {
	return file_proto_plugin_proto_rawDescGZIP(), []int{4}
}

func (x *DiscoverRequest) GetConfigJson() []byte {
	if x != nil {
		return x.ConfigJson
	}
	return nil
}

type DiscoverResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// JSON-encoded pluginsdk.DiscoveryResult
	ResultJson    []byte `protobuf:"bytes,1,opt,name=result_json,json=resultJson,proto3" json:"result_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DiscoverResponse) Reset() {
	*x = DiscoverResponse{}
	mi := &file_proto_plugin_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiscoverResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiscoverResponse) ProtoMessage() {}

func (x *DiscoverResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_plugin_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiscoverResponse.ProtoReflect.Descriptor instead.
func (*DiscoverResponse) Descriptor() ([]byte, []int) {
	return file_proto_plugin_proto_rawDescGZIP(), []int{5}
}

func (x *DiscoverResponse) GetResultJson() []byte {
	if x != nil {
		return x.ResultJson
	}
	return nil
}

type FetchSampleDataRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// JSON-encoded raw plugin config
	ConfigJson []byte `protobuf:"bytes,1,opt,name=config_json,json=configJson,proto3" json:"config_json,omitempty"`
	// JSON-encoded pluginsdk.Asset to fetch sample data for
	AssetJson     []byte `protobuf:"bytes,2,opt,name=asset_json,json=assetJson,proto3" json:"asset_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FetchSampleDataRequest) Reset() {
	*x = FetchSampleDataRequest{}
	mi := &file_proto_plugin_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchSampleDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchSampleDataRequest) ProtoMessage() {}

func (x *FetchSampleDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_plugin_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchSampleDataRequest.ProtoReflect.Descriptor instead.
func (*FetchSampleDataRequest) Descriptor() ([]byte, []int) {
	return file_proto_plugin_proto_rawDescGZIP(), []int{6}
}

func (x *FetchSampleDataRequest) GetConfigJson() []byte {
	if x != nil {
		return x.ConfigJson
	}
	return nil
}

func (x *FetchSampleDataRequest) GetAssetJson() []byte {
	if x != nil {
		return x.AssetJson
	}
	return nil
}

type FetchSampleDataResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// JSON-encoded pluginsdk.SampleData
	ResultJson    []byte `protobuf:"bytes,1,opt,name=result_json,json=resultJson,proto3" json:"result_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FetchSampleDataResponse) Reset() {
	*x = FetchSampleDataResponse{}
	mi := &file_proto_plugin_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchSampleDataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchSampleDataResponse) ProtoMessage() {}

func (x *FetchSampleDataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_plugin_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchSampleDataResponse.ProtoReflect.Descriptor instead.
func (*FetchSampleDataResponse) Descriptor() ([]byte, []int) {
	return file_proto_plugin_proto_rawDescGZIP(), []int{7}
}

func (x *FetchSampleDataResponse) GetResultJson() []byte {
	if x != nil {
		return x.ResultJson
	}
	return nil
}

type PlanQueryRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// JSON-encoded raw plugin config
	ConfigJson []byte `protobuf:"bytes,1,opt,name=config_json,json=configJson,proto3" json:"config_json,omitempty"`
	// JSON-encoded pluginsdk.QueryRequest
	QueryJson     []byte `protobuf:"bytes,2,opt,name=query_json,json=queryJson,proto3" json:"query_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlanQueryRequest) Reset() {
	*x = PlanQueryRequest{}
	mi := &file_proto_plugin_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlanQueryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlanQueryRequest) ProtoMessage() {}

func (x *PlanQueryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_plugin_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlanQueryRequest.ProtoReflect.Descriptor instead.
func (*PlanQueryRequest) Descriptor() ([]byte, []int) {
	return file_proto_plugin_proto_rawDescGZIP(), []int{8}
}

func (x *PlanQueryRequest) GetConfigJson() []byte {
	if x != nil {
		return x.ConfigJson
	}
	return nil
}

func (x *PlanQueryRequest) GetQueryJson() []byte {
	if x != nil {
		return x.QueryJson
	}
	return nil
}

type PlanQueryResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// JSON-encoded pluginsdk.QueryPlan; empty when the engine cannot plan
	// the statement and the host should fall back to target-level policy
	PlanJson      []byte `protobuf:"bytes,1,opt,name=plan_json,json=planJson,proto3" json:"plan_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlanQueryResponse) Reset() {
	*x = PlanQueryResponse{}
	mi := &file_proto_plugin_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlanQueryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlanQueryResponse) ProtoMessage() {}

func (x *PlanQueryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_plugin_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlanQueryResponse.ProtoReflect.Descriptor instead.
func (*PlanQueryResponse) Descriptor() ([]byte, []int) {
	return file_proto_plugin_proto_rawDescGZIP(), []int{9}
}

func (x *PlanQueryResponse) GetPlanJson() []byte {
	if x != nil {
		return x.PlanJson
	}
	return nil
}

type ExecuteQueryRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// JSON-encoded raw plugin config
	ConfigJson []byte `protobuf:"bytes,1,opt,name=config_json,json=configJson,proto3" json:"config_json,omitempty"`
	// JSON-encoded pluginsdk.QueryRequest
	QueryJson     []byte `protobuf:"bytes,2,opt,name=query_json,json=queryJson,proto3" json:"query_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteQueryRequest) Reset() {
	*x = ExecuteQueryRequest{}
	mi := &file_proto_plugin_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteQueryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteQueryRequest) ProtoMessage() {}

func (x *ExecuteQueryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_plugin_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteQueryRequest.ProtoReflect.Descriptor instead.
func (*ExecuteQueryRequest) Descriptor() ([]byte, []int) {
	return file_proto_plugin_proto_rawDescGZIP(), []int{10}
}

func (x *ExecuteQueryRequest) GetConfigJson() []byte {
	if x != nil {
		return x.ConfigJson
	}
	return nil
}

func (x *ExecuteQueryRequest) GetQueryJson() []byte {
	if x != nil {
		return x.QueryJson
	}
	return nil
}

type ExecuteQueryChunk struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// JSON-encoded pluginsdk.QueryResultChunk
	ChunkJson     []byte `protobuf:"bytes,1,opt,name=chunk_json,json=chunkJson,proto3" json:"chunk_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteQueryChunk) Reset() {
	*x = ExecuteQueryChunk{}
	mi := &file_proto_plugin_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteQueryChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteQueryChunk) ProtoMessage() {}

func (x *ExecuteQueryChunk) ProtoReflect() protoreflect.Message {
	mi := &file_proto_plugin_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteQueryChunk.ProtoReflect.Descriptor instead.
func (*ExecuteQueryChunk) Descriptor() ([]byte, []int) {
	return file_proto_plugin_proto_rawDescGZIP(), []int{11}
}

func (x *ExecuteQueryChunk) GetChunkJson() []byte {
	if x != nil {
		return x.ChunkJson
	}
	return nil
}

var File_proto_plugin_proto protoreflect.FileDescriptor

const file_proto_plugin_proto_rawDesc = "" +
	"\n" +
	"\x12proto/plugin.proto\x12\x10marmot.plugin.v1\"\x10\n" +
	"\x0eGetMetaRequest\".\n" +
	"\x0fGetMetaResponse\x12\x1b\n" +
	"\tmeta_json\x18\x01 \x01(\fR\bmetaJson\"2\n" +
	"\x0fValidateRequest\x12\x1f\n" +
	"\vconfig_json\x18\x01 \x01(\fR\n" +
	"configJson\"3\n" +
	"\x10ValidateResponse\x12\x1f\n" +
	"\vconfig_json\x18\x01 \x01(\fR\n" +
	"configJson\"2\n" +
	"\x0fDiscoverRequest\x12\x1f\n" +
	"\vconfig_json\x18\x01 \x01(\fR\n" +
	"configJson\"3\n" +
	"\x10DiscoverResponse\x12\x1f\n" +
	"\vresult_json\x18\x01 \x01(\fR\n" +
	"resultJson\"X\n" +
	"\x16FetchSampleDataRequest\x12\x1f\n" +
	"\vconfig_json\x18\x01 \x01(\fR\n" +
	"configJson\x12\x1d\n" +
	"\n" +
	"asset_json\x18\x02 \x01(\fR\tassetJson\":\n" +
	"\x17FetchSampleDataResponse\x12\x1f\n" +
	"\vresult_json\x18\x01 \x01(\fR\n" +
	"resultJson\"R\n" +
	"\x10PlanQueryRequest\x12\x1f\n" +
	"\vconfig_json\x18\x01 \x01(\fR\n" +
	"configJson\x12\x1d\n" +
	"\n" +
	"query_json\x18\x02 \x01(\fR\tqueryJson\"0\n" +
	"\x11PlanQueryResponse\x12\x1b\n" +
	"\tplan_json\x18\x01 \x01(\fR\bplanJson\"U\n" +
	"\x13ExecuteQueryRequest\x12\x1f\n" +
	"\vconfig_json\x18\x01 \x01(\fR\n" +
	"configJson\x12\x1d\n" +
	"\n" +
	"query_json\x18\x02 \x01(\fR\tqueryJson\"2\n" +
	"\x11ExecuteQueryChunk\x12\x1d\n" +
	"\n" +
	"chunk_json\x18\x01 \x01(\fR\tchunkJson2\x9a\x04\n" +
	"\x06Source\x12N\n" +
	"\aGetMeta\x12 .marmot.plugin.v1.GetMetaRequest\x1a!.marmot.plugin.v1.GetMetaResponse\x12Q\n" +
	"\bValidate\x12!.marmot.plugin.v1.ValidateRequest\x1a\".marmot.plugin.v1.ValidateResponse\x12Q\n" +
	"\bDiscover\x12!.marmot.plugin.v1.DiscoverRequest\x1a\".marmot.plugin.v1.DiscoverResponse\x12f\n" +
	"\x0fFetchSampleData\x12(.marmot.plugin.v1.FetchSampleDataRequest\x1a).marmot.plugin.v1.FetchSampleDataResponse\x12T\n" +
	"\tPlanQuery\x12\".marmot.plugin.v1.PlanQueryRequest\x1a#.marmot.plugin.v1.PlanQueryResponse\x12\\\n" +
	"\fExecuteQuery\x12%.marmot.plugin.v1.ExecuteQueryRequest\x1a#.marmot.plugin.v1.ExecuteQueryChunk0\x01B(Z&github.com/marmotdata/plugin-sdk/protob\x06proto3"

var (
	file_proto_plugin_proto_rawDescOnce sync.Once
	file_proto_plugin_proto_rawDescData []byte
)

func file_proto_plugin_proto_rawDescGZIP() []byte {
	file_proto_plugin_proto_rawDescOnce.Do(func() {
		file_proto_plugin_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_plugin_proto_rawDesc), len(file_proto_plugin_proto_rawDesc)))
	})
	return file_proto_plugin_proto_rawDescData
}

var file_proto_plugin_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_proto_plugin_proto_goTypes = []any{
	(*GetMetaRequest)(nil),          // 0: marmot.plugin.v1.GetMetaRequest
	(*GetMetaResponse)(nil),         // 1: marmot.plugin.v1.GetMetaResponse
	(*ValidateRequest)(nil),         // 2: marmot.plugin.v1.ValidateRequest
	(*ValidateResponse)(nil),        // 3: marmot.plugin.v1.ValidateResponse
	(*DiscoverRequest)(nil),         // 4: marmot.plugin.v1.DiscoverRequest
	(*DiscoverResponse)(nil),        // 5: marmot.plugin.v1.DiscoverResponse
	(*FetchSampleDataRequest)(nil),  // 6: marmot.plugin.v1.FetchSampleDataRequest
	(*FetchSampleDataResponse)(nil), // 7: marmot.plugin.v1.FetchSampleDataResponse
	(*PlanQueryRequest)(nil),        // 8: marmot.plugin.v1.PlanQueryRequest
	(*PlanQueryResponse)(nil),       // 9: marmot.plugin.v1.PlanQueryResponse
	(*ExecuteQueryRequest)(nil),     // 10: marmot.plugin.v1.ExecuteQueryRequest
	(*ExecuteQueryChunk)(nil),       // 11: marmot.plugin.v1.ExecuteQueryChunk
}
var file_proto_plugin_proto_depIdxs = []int32{
	0,  // 0: marmot.plugin.v1.Source.GetMeta:input_type -> marmot.plugin.v1.GetMetaRequest
	2,  // 1: marmot.plugin.v1.Source.Validate:input_type -> marmot.plugin.v1.ValidateRequest
	4,  // 2: marmot.plugin.v1.Source.Discover:input_type -> marmot.plugin.v1.DiscoverRequest
	6,  // 3: marmot.plugin.v1.Source.FetchSampleData:input_type -> marmot.plugin.v1.FetchSampleDataRequest
	8,  // 4: marmot.plugin.v1.Source.PlanQuery:input_type -> marmot.plugin.v1.PlanQueryRequest
	10, // 5: marmot.plugin.v1.Source.ExecuteQuery:input_type -> marmot.plugin.v1.ExecuteQueryRequest
	1,  // 6: marmot.plugin.v1.Source.GetMeta:output_type -> marmot.plugin.v1.GetMetaResponse
	3,  // 7: marmot.plugin.v1.Source.Validate:output_type -> marmot.plugin.v1.ValidateResponse
	5,  // 8: marmot.plugin.v1.Source.Discover:output_type -> marmot.plugin.v1.DiscoverResponse
	7,  // 9: marmot.plugin.v1.Source.FetchSampleData:output_type -> marmot.plugin.v1.FetchSampleDataResponse
	9,  // 10: marmot.plugin.v1.Source.PlanQuery:output_type -> marmot.plugin.v1.PlanQueryResponse
	11, // 11: marmot.plugin.v1.Source.ExecuteQuery:output_type -> marmot.plugin.v1.ExecuteQueryChunk
	6,  // [6:12] is the sub-list for method output_type
	0,  // [0:6] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_proto_plugin_proto_init() }
func file_proto_plugin_proto_init() {
	if File_proto_plugin_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_plugin_proto_rawDesc), len(file_proto_plugin_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_plugin_proto_goTypes,
		DependencyIndexes: file_proto_plugin_proto_depIdxs,
		MessageInfos:      file_proto_plugin_proto_msgTypes,
	}.Build()
	File_proto_plugin_proto = out.File
	file_proto_plugin_proto_goTypes = nil
	file_proto_plugin_proto_depIdxs = nil
}
