// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.36.0
// source: proto/plugin.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Source_GetMeta_FullMethodName         = "/marmot.plugin.v1.Source/GetMeta"
	Source_Validate_FullMethodName        = "/marmot.plugin.v1.Source/Validate"
	Source_Discover_FullMethodName        = "/marmot.plugin.v1.Source/Discover"
	Source_FetchSampleData_FullMethodName = "/marmot.plugin.v1.Source/FetchSampleData"
	Source_PlanQuery_FullMethodName       = "/marmot.plugin.v1.Source/PlanQuery"
	Source_ExecuteQuery_FullMethodName    = "/marmot.plugin.v1.Source/ExecuteQuery"
)

// SourceClient is the client API for Source service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Source is the gRPC service every Marmot plugin exposes over go-plugin.
// Config, metadata, and discovery payloads are JSON-encoded so the wire
// protocol stays stable while plugin-facing Go types evolve.
type SourceClient interface {
	GetMeta(ctx context.Context, in *GetMetaRequest, opts ...grpc.CallOption) (*GetMetaResponse, error)
	Validate(ctx context.Context, in *ValidateRequest, opts ...grpc.CallOption) (*ValidateResponse, error)
	Discover(ctx context.Context, in *DiscoverRequest, opts ...grpc.CallOption) (*DiscoverResponse, error)
	// FetchSampleData is optional; plugins whose source does not implement
	// DataFetcher respond with UNIMPLEMENTED.
	FetchSampleData(ctx context.Context, in *FetchSampleDataRequest, opts ...grpc.CallOption) (*FetchSampleDataResponse, error)
	// PlanQuery and ExecuteQuery are optional; plugins whose source does not
	// implement Querier respond with UNIMPLEMENTED.
	PlanQuery(ctx context.Context, in *PlanQueryRequest, opts ...grpc.CallOption) (*PlanQueryResponse, error)
	ExecuteQuery(ctx context.Context, in *ExecuteQueryRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ExecuteQueryChunk], error)
}

type sourceClient struct {
	cc grpc.ClientConnInterface
}

func NewSourceClient(cc grpc.ClientConnInterface) SourceClient {
	return &sourceClient{cc}
}

func (c *sourceClient) GetMeta(ctx context.Context, in *GetMetaRequest, opts ...grpc.CallOption) (*GetMetaResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetMetaResponse)
	err := c.cc.Invoke(ctx, Source_GetMeta_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sourceClient) Validate(ctx context.Context, in *ValidateRequest, opts ...grpc.CallOption) (*ValidateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ValidateResponse)
	err := c.cc.Invoke(ctx, Source_Validate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sourceClient) Discover(ctx context.Context, in *DiscoverRequest, opts ...grpc.CallOption) (*DiscoverResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DiscoverResponse)
	err := c.cc.Invoke(ctx, Source_Discover_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sourceClient) FetchSampleData(ctx context.Context, in *FetchSampleDataRequest, opts ...grpc.CallOption) (*FetchSampleDataResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FetchSampleDataResponse)
	err := c.cc.Invoke(ctx, Source_FetchSampleData_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sourceClient) PlanQuery(ctx context.Context, in *PlanQueryRequest, opts ...grpc.CallOption) (*PlanQueryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PlanQueryResponse)
	err := c.cc.Invoke(ctx, Source_PlanQuery_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sourceClient) ExecuteQuery(ctx context.Context, in *ExecuteQueryRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ExecuteQueryChunk], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Source_ServiceDesc.Streams[0], Source_ExecuteQuery_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ExecuteQueryRequest, ExecuteQueryChunk]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Source_ExecuteQueryClient = grpc.ServerStreamingClient[ExecuteQueryChunk]

// SourceServer is the server API for Source service.
// All implementations must embed UnimplementedSourceServer
// for forward compatibility.
//
// Source is the gRPC service every Marmot plugin exposes over go-plugin.
// Config, metadata, and discovery payloads are JSON-encoded so the wire
// protocol stays stable while plugin-facing Go types evolve.
type SourceServer interface {
	GetMeta(context.Context, *GetMetaRequest) (*GetMetaResponse, error)
	Validate(context.Context, *ValidateRequest) (*ValidateResponse, error)
	Discover(context.Context, *DiscoverRequest) (*DiscoverResponse, error)
	// FetchSampleData is optional; plugins whose source does not implement
	// DataFetcher respond with UNIMPLEMENTED.
	FetchSampleData(context.Context, *FetchSampleDataRequest) (*FetchSampleDataResponse, error)
	// PlanQuery and ExecuteQuery are optional; plugins whose source does not
	// implement Querier respond with UNIMPLEMENTED.
	PlanQuery(context.Context, *PlanQueryRequest) (*PlanQueryResponse, error)
	ExecuteQuery(*ExecuteQueryRequest, grpc.ServerStreamingServer[ExecuteQueryChunk]) error
	mustEmbedUnimplementedSourceServer()
}

// UnimplementedSourceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSourceServer struct{}

func (UnimplementedSourceServer) GetMeta(context.Context, *GetMetaRequest) (*GetMetaResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetMeta not implemented")
}
func (UnimplementedSourceServer) Validate(context.Context, *ValidateRequest) (*ValidateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Validate not implemented")
}
func (UnimplementedSourceServer) Discover(context.Context, *DiscoverRequest) (*DiscoverResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Discover not implemented")
}
func (UnimplementedSourceServer) FetchSampleData(context.Context, *FetchSampleDataRequest) (*FetchSampleDataResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method FetchSampleData not implemented")
}
func (UnimplementedSourceServer) PlanQuery(context.Context, *PlanQueryRequest) (*PlanQueryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PlanQuery not implemented")
}
func (UnimplementedSourceServer) ExecuteQuery(*ExecuteQueryRequest, grpc.ServerStreamingServer[ExecuteQueryChunk]) error {
	return status.Error(codes.Unimplemented, "method ExecuteQuery not implemented")
}
func (UnimplementedSourceServer) mustEmbedUnimplementedSourceServer() {}
func (UnimplementedSourceServer) testEmbeddedByValue()                {}

// UnsafeSourceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SourceServer will
// result in compilation errors.
type UnsafeSourceServer interface {
	mustEmbedUnimplementedSourceServer()
}

func RegisterSourceServer(s grpc.ServiceRegistrar, srv SourceServer) {
	// If the following call panics, it indicates UnimplementedSourceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Source_ServiceDesc, srv)
}

func _Source_GetMeta_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMetaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SourceServer).GetMeta(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Source_GetMeta_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SourceServer).GetMeta(ctx, req.(*GetMetaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Source_Validate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ValidateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SourceServer).Validate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Source_Validate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SourceServer).Validate(ctx, req.(*ValidateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Source_Discover_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DiscoverRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SourceServer).Discover(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Source_Discover_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SourceServer).Discover(ctx, req.(*DiscoverRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Source_FetchSampleData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FetchSampleDataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SourceServer).FetchSampleData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Source_FetchSampleData_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SourceServer).FetchSampleData(ctx, req.(*FetchSampleDataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Source_PlanQuery_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PlanQueryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SourceServer).PlanQuery(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Source_PlanQuery_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SourceServer).PlanQuery(ctx, req.(*PlanQueryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Source_ExecuteQuery_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ExecuteQueryRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(SourceServer).ExecuteQuery(m, &grpc.GenericServerStream[ExecuteQueryRequest, ExecuteQueryChunk]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Source_ExecuteQueryServer = grpc.ServerStreamingServer[ExecuteQueryChunk]

// Source_ServiceDesc is the grpc.ServiceDesc for Source service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Source_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "marmot.plugin.v1.Source",
	HandlerType: (*SourceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetMeta",
			Handler:    _Source_GetMeta_Handler,
		},
		{
			MethodName: "Validate",
			Handler:    _Source_Validate_Handler,
		},
		{
			MethodName: "Discover",
			Handler:    _Source_Discover_Handler,
		},
		{
			MethodName: "FetchSampleData",
			Handler:    _Source_FetchSampleData_Handler,
		},
		{
			MethodName: "PlanQuery",
			Handler:    _Source_PlanQuery_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ExecuteQuery",
			Handler:       _Source_ExecuteQuery_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "proto/plugin.proto",
}
